// <auto-generated />
using System;
using BingoSim.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BingoSim.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202005206_AddTeamsAndStrategy")]
    partial class AddTeamsAndStrategy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BingoSim.Core.Entities.ActivityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ActivityDefinitions", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UnlockPointsRequiredPerRow")
                        .HasColumnType("integer");

                    b.Property<string>("_rowsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Rows");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SkillTimeMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.StrategyConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ParamsJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("StrategyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("StrategyConfigs", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.TeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("TeamId", "PlayerProfileId")
                        .IsUnique();

                    b.ToTable("TeamPlayers", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.ActivityDefinition", b =>
                {
                    b.OwnsMany("BingoSim.Core.ValueObjects.ActivityAttemptDefinition", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("ActivityDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("RollScope")
                                .HasColumnType("integer");

                            b1.HasKey("ActivityDefinitionId", "__synthesizedOrdinal");

                            b1.ToTable("ActivityDefinitions");

                            b1.ToJson("Attempts");

                            b1.WithOwner()
                                .HasForeignKey("ActivityDefinitionId");

                            b1.OwnsMany("BingoSim.Core.ValueObjects.ActivityOutcomeDefinition", "Outcomes", b2 =>
                                {
                                    b2.Property<Guid>("ActivityAttemptDefinitionActivityDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ActivityAttemptDefinition__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<int>("WeightDenominator")
                                        .HasColumnType("integer");

                                    b2.Property<int>("WeightNumerator")
                                        .HasColumnType("integer");

                                    b2.HasKey("ActivityAttemptDefinitionActivityDefinitionId", "ActivityAttemptDefinition__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ActivityDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("ActivityAttemptDefinitionActivityDefinitionId", "ActivityAttemptDefinition__synthesizedOrdinal");

                                    b2.OwnsMany("BingoSim.Core.ValueObjects.ProgressGrant", "Grants", b3 =>
                                        {
                                            b3.Property<Guid>("ActivityOutcomeDefinitionActivityAttemptDefinitionActivityDefinitionId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("ActivityOutcomeDefinitionActivityAttemptDefinitionActivityDefi~");

                                            b3.Property<int>("ActivityOutcomeDefinitionActivityAttemptDefinition__synthesizedOrdinal")
                                                .HasColumnType("integer")
                                                .HasColumnName("ActivityOutcomeDefinitionActivityAttemptDefinition__synthesize~");

                                            b3.Property<int>("ActivityOutcomeDefinition__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<string>("DropKey")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)");

                                            b3.Property<int>("Units")
                                                .HasColumnType("integer");

                                            b3.HasKey("ActivityOutcomeDefinitionActivityAttemptDefinitionActivityDefinitionId", "ActivityOutcomeDefinitionActivityAttemptDefinition__synthesizedOrdinal", "ActivityOutcomeDefinition__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("ActivityDefinitions");

                                            b3.WithOwner()
                                                .HasForeignKey("ActivityOutcomeDefinitionActivityAttemptDefinitionActivityDefinitionId", "ActivityOutcomeDefinitionActivityAttemptDefinition__synthesizedOrdinal", "ActivityOutcomeDefinition__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Grants");
                                });

                            b1.OwnsOne("BingoSim.Core.ValueObjects.AttemptTimeModel", "TimeModel", b2 =>
                                {
                                    b2.Property<Guid>("ActivityAttemptDefinitionActivityDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ActivityAttemptDefinition__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("BaselineTimeSeconds")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Distribution")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("VarianceSeconds")
                                        .HasColumnType("integer");

                                    b2.HasKey("ActivityAttemptDefinitionActivityDefinitionId", "ActivityAttemptDefinition__synthesizedOrdinal");

                                    b2.ToTable("ActivityDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("ActivityAttemptDefinitionActivityDefinitionId", "ActivityAttemptDefinition__synthesizedOrdinal");
                                });

                            b1.Navigation("Outcomes");

                            b1.Navigation("TimeModel")
                                .IsRequired();
                        });

                    b.OwnsOne("BingoSim.Core.ValueObjects.ActivityModeSupport", "ModeSupport", b1 =>
                        {
                            b1.Property<Guid>("ActivityDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxGroupSize")
                                .HasColumnType("integer");

                            b1.Property<int?>("MinGroupSize")
                                .HasColumnType("integer");

                            b1.Property<bool>("SupportsGroup")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsSolo")
                                .HasColumnType("boolean");

                            b1.HasKey("ActivityDefinitionId");

                            b1.ToTable("ActivityDefinitions");

                            b1.ToJson("ModeSupport");

                            b1.WithOwner()
                                .HasForeignKey("ActivityDefinitionId");
                        });

                    b.OwnsMany("BingoSim.Core.ValueObjects.GroupSizeBand", "GroupScalingBands", b1 =>
                        {
                            b1.Property<Guid>("ActivityDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("MaxSize")
                                .HasColumnType("integer");

                            b1.Property<int>("MinSize")
                                .HasColumnType("integer");

                            b1.Property<decimal>("ProbabilityMultiplier")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<decimal>("TimeMultiplier")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.HasKey("ActivityDefinitionId", "__synthesizedOrdinal");

                            b1.ToTable("ActivityDefinitions");

                            b1.ToJson("GroupScalingBands");

                            b1.WithOwner()
                                .HasForeignKey("ActivityDefinitionId");
                        });

                    b.Navigation("Attempts");

                    b.Navigation("GroupScalingBands");

                    b.Navigation("ModeSupport")
                        .IsRequired();
                });

            modelBuilder.Entity("BingoSim.Core.Entities.PlayerProfile", b =>
                {
                    b.OwnsMany("BingoSim.Core.ValueObjects.Capability", "Capabilities", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("PlayerProfileId", "__synthesizedOrdinal");

                            b1.ToTable("PlayerProfiles");

                            b1.ToJson("Capabilities");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");
                        });

                    b.OwnsOne("BingoSim.Core.ValueObjects.WeeklySchedule", "WeeklySchedule", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.HasKey("PlayerProfileId");

                            b1.ToTable("PlayerProfiles");

                            b1.ToJson("WeeklySchedule");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");

                            b1.OwnsMany("BingoSim.Core.ValueObjects.ScheduledSession", "Sessions", b2 =>
                                {
                                    b2.Property<Guid>("WeeklySchedulePlayerProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer");

                                    b2.Property<int>("DurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<TimeOnly>("StartLocalTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("WeeklySchedulePlayerProfileId", "__synthesizedOrdinal");

                                    b2.ToTable("PlayerProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklySchedulePlayerProfileId");
                                });

                            b1.Navigation("Sessions");
                        });

                    b.Navigation("Capabilities");

                    b.Navigation("WeeklySchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("BingoSim.Core.Entities.StrategyConfig", b =>
                {
                    b.HasOne("BingoSim.Core.Entities.Team", "Team")
                        .WithOne("StrategyConfig")
                        .HasForeignKey("BingoSim.Core.Entities.StrategyConfig", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BingoSim.Core.Entities.TeamPlayer", b =>
                {
                    b.HasOne("BingoSim.Core.Entities.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BingoSim.Core.Entities.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BingoSim.Core.Entities.Team", b =>
                {
                    b.Navigation("StrategyConfig");

                    b.Navigation("TeamPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
