// <auto-generated />
using System;
using BingoSim.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BingoSim.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201024553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BingoSim.Core.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SkillTimeMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("BingoSim.Core.Entities.PlayerProfile", b =>
                {
                    b.OwnsMany("BingoSim.Core.ValueObjects.Capability", "Capabilities", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("PlayerProfileId", "__synthesizedOrdinal");

                            b1.ToTable("PlayerProfiles");

                            b1.ToJson("Capabilities");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");
                        });

                    b.OwnsOne("BingoSim.Core.ValueObjects.WeeklySchedule", "WeeklySchedule", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.HasKey("PlayerProfileId");

                            b1.ToTable("PlayerProfiles");

                            b1.ToJson("WeeklySchedule");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");

                            b1.OwnsMany("BingoSim.Core.ValueObjects.ScheduledSession", "Sessions", b2 =>
                                {
                                    b2.Property<Guid>("WeeklySchedulePlayerProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer");

                                    b2.Property<int>("DurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<TimeOnly>("StartLocalTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("WeeklySchedulePlayerProfileId", "__synthesizedOrdinal");

                                    b2.ToTable("PlayerProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklySchedulePlayerProfileId");
                                });

                            b1.Navigation("Sessions");
                        });

                    b.Navigation("Capabilities");

                    b.Navigation("WeeklySchedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
